[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.7.0"
  NODE_ENV = "production"
  NETLIFY_USE_YARN = "true"
  YARN_ENABLE_GLOBAL_CACHE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "@netlify/plugin-cachedir"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 